aliases:
  - &node_executor
    executor:
      name: node/node
      node-version: "18.19"

version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  node: bigcommerce/internal-node@volatile

jobs:
  build:
    <<: *node_executor

    steps:
      - ci/pre-setup

      - restore_cache:
          keys:
            - memoize-js

      - run: npm ci

      - save_cache:
          key: memoize-js
          paths:
            - ~/.npm

      - run:
          name: Test
          command: npm run test:series -- --coverage
          when: always

      - store_artifacts:
          path: coverage
          destination: coverage

      - run:
          name: Lint
          command: npm run lint
          when: always

      - run:
          name: Validate commits
          command: npm run validate-commits
          when: always
